# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('OFFER_READY', 'Offer Ready'), ('DISBURSEMENT', 'Disbursement'), ('REPAYMENT_REMINDER', 'Repayment Reminder'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYOFF', 'Payoff'), ('ADMIN_NOTIFICATION', 'Admin Notification'), ('MANUAL', 'Manual')], max_length=30)),
                ('recipient_phone_e164', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('reminder_business_date', models.DateField(blank=True, null=True)),
                ('reminder_slot', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('provider_response_code', models.CharField(blank=True, max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_summary', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='loans.repaymentinstallment')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='messaging_s_status_4fef94_idx'), models.Index(fields=['scheduled_for'], name='messaging_s_schedul_a8051e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('installment__isnull', False), ('reminder_business_date__isnull', False)), fields=('installment', 'message_type', 'reminder_business_date', 'reminder_slot'), name='smsmessage_unique_scheduled_reminder')],
            },
        ),
    ]
