# Generated by Django 5.2.16 on 2026-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='message_type',
            field=models.CharField(choices=[('LOAN_OFFER_READY', 'Loan Offer Ready'), ('OFFER_ACCEPTED_CUSTOMER', 'Offer Accepted (Customer)'), ('OFFER_ACCEPTED_ADMIN', 'Offer Accepted (Admin)'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_DISBURSED_CUSTOMER', 'Loan Disbursed (Customer)'), ('LOAN_DISBURSED_ADMIN', 'Loan Disbursed (Admin)'), ('PAYMENT_RECEIVED_CUSTOMER', 'Payment Received (Customer)'), ('PAYMENT_RECEIVED_ADMIN', 'Payment Received (Admin)'), ('REPAYMENT_DUE_5_DAYS', 'Repayment Due in 5 Days'), ('REPAYMENT_DUE_3_DAYS', 'Repayment Due in 3 Days'), ('REPAYMENT_DUE_2_DAYS', 'Repayment Due in 2 Days'), ('REPAYMENT_DUE_1_DAY', 'Repayment Due in 1 Day'), ('REPAYMENT_DUE_TODAY_MORNING', 'Repayment Due Today (Morning)'), ('REPAYMENT_DUE_TODAY_AFTERNOON', 'Repayment Due Today (Afternoon)'), ('REPAYMENT_OVERDUE', 'Repayment Overdue'), ('LOAN_PAID_OFF_CUSTOMER', 'Loan Paid Off (Customer)'), ('LOAN_PAID_OFF_ADMIN', 'Loan Paid Off (Admin)'), ('MANUAL_REMINDER', 'Manual Reminder')], max_length=30),
        ),
    ]
