# Generated by Django 5.2.16 on 2026-07-26 22:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_smsmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=10, unique=True)),
                ('hubtel_enabled', models.BooleanField(default=True)),
                ('morning_reminder_time', models.TimeField(default=datetime.time(8, 0))),
                ('afternoon_reminder_time', models.TimeField(default=datetime.time(16, 0))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
