# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SUPERSEDED', 'Superseded'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_method', models.CharField(choices=[('FLAT_TOTAL_TERM', 'Flat Total-Term Interest')], default='FLAT_TOTAL_TERM', max_length=20)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('term_count', models.PositiveIntegerField()),
                ('term_unit', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month')], max_length=10)),
                ('first_due_date', models.DateField()),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_repayable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_count', models.PositiveIntegerField()),
                ('offer_expiry_date', models.DateField(blank=True, null=True)),
                ('customer_terms', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='loan_requests.loanrequest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['loan_request', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='OfferInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loan_offers.loanoffer')),
            ],
            options={
                'ordering': ['offer', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['loan_request', 'status'], name='loan_offers_loan_re_09bb2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanoffer',
            constraint=models.UniqueConstraint(fields=('loan_request', 'version_number'), name='loanoffer_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='loanoffer',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loanoffer_principal_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loanoffer',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate_percent__gte', 0)), name='loanoffer_interest_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='loanoffer',
            constraint=models.CheckConstraint(condition=models.Q(('term_count__gt', 0), ('term_count__lte', 60)), name='loanoffer_term_count_bounds'),
        ),
        migrations.AddConstraint(
            model_name='offerinstallment',
            constraint=models.UniqueConstraint(fields=('offer', 'sequence_number'), name='offerinstallment_unique_sequence'),
        ),
    ]
