# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        ('loan_offers', '0001_initial'),
        ('loan_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED_FOR_DISBURSEMENT', 'Approved for Disbursement'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('OVERDUE', 'Overdue'), ('RESTRUCTURED', 'Restructured'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=25)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_repayable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loan_offers.loanoffer')),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='agreements.agreement')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loan_requests.loanrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank')], max_length=20)),
                ('masked_payout_snapshot', models.JSONField(blank=True, default=dict)),
                ('external_transaction_reference', models.CharField(blank=True, max_length=100)),
                ('evidence_file_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_disbursements', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='UPCOMING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='loans_loan_custome_9efb67_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loan_principal_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_balance__gte', 0)), name='loan_outstanding_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('amount_disbursed__gte', 0)), name='loan_amount_disbursed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('amount_repaid__gte', 0)), name='loan_amount_repaid_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.UniqueConstraint(fields=('loan',), name='disbursement_one_per_loan_mvp'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_reference', ''), _negated=True), fields=('external_transaction_reference',), name='disbursement_unique_reference_when_set'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='disbursement_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='repaymentinstallment',
            index=models.Index(fields=['loan', 'status'], name='loans_repay_loan_id_3586cf_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentinstallment',
            index=models.Index(fields=['due_date'], name='loans_repay_due_dat_71f4b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'sequence_number'), name='repaymentinstallment_unique_sequence'),
        ),
    ]
