# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typed_legal_name', models.CharField(max_length=255)),
                ('acceptance_text_version', models.CharField(max_length=20)),
                ('acceptance_text_snapshot', models.TextField()),
                ('signature_image_path', models.CharField(blank=True, max_length=500)),
                ('signature_image_sha256', models.CharField(blank=True, max_length=64)),
                ('agreement_pdf_path', models.CharField(blank=True, max_length=500)),
                ('agreement_pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('accepted_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_user_agent', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField()),
                ('email_delivery_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=10)),
                ('email_provider_reference', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='loan_offers.loanoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
