# Generated by Django 5.2.16 on 2026-07-24 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number_e164', models.CharField(max_length=20)),
                ('phone_country_code', models.CharField(max_length=4)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='GH', max_length=2)),
                ('preferred_disbursement_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank')], max_length=20)),
                ('mobile_money_network', models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('TELECEL', 'Telecel Cash'), ('AIRTELTIGO', 'AirtelTigo Money'), ('OTHER', 'Other')], max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('profile_completed_at__isnull', True), models.Q(('preferred_disbursement_method', 'MOBILE_MONEY'), models.Q(('mobile_money_network', ''), _negated=True), models.Q(('mobile_money_number', ''), _negated=True)), models.Q(('preferred_disbursement_method', 'BANK'), models.Q(('bank_name', ''), _negated=True), models.Q(('bank_account_name', ''), _negated=True), models.Q(('bank_account_number', ''), _negated=True)), _connector='OR'), name='customerprofile_payout_fields_required_when_completed')],
            },
        ),
    ]
