# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('requested_term_count', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_term_unit', models.CharField(blank=True, choices=[('WEEK', 'Week'), ('MONTH', 'Month')], max_length=10)),
                ('payout_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('OFFER_SENT', 'Offer Sent'), ('CUSTOMER_ACCEPTED', 'Customer Accepted'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('CONVERTED_TO_LOAN', 'Converted to Loan')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loan_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='loan_reques_custome_663390_idx'), models.Index(fields=['status'], name='loan_reques_status_c7e435_idx')],
            },
        ),
    ]
