# Generated by Django 5.2.16 on 2026-07-24 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=20)),
                ('external_transaction_reference', models.CharField(blank=True, max_length=100)),
                ('evidence_file_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('reversal_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='repayments.payment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.repaymentinstallment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='repayments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('REPAYMENT', 'Repayment'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write Off')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('source_object_type', models.CharField(max_length=100)),
                ('source_object_id', models.CharField(max_length=64)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['loan', 'created_at'],
                'indexes': [models.Index(fields=['loan', 'created_at'], name='repayments__loan_id_2aea2d_idx'), models.Index(fields=['source_object_type', 'source_object_id'], name='repayments__source__9f7b81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan', 'status'], name='repayments__loan_id_2d2aa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_reference', ''), _negated=True), fields=('external_transaction_reference',), name='payment_unique_reference_when_set'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='payment_unique_idempotency_key_when_set'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'installment'), name='paymentallocation_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='paymentallocation_total_gt_0'),
        ),
    ]
