# Generated by Django 5.2.16 on 2026-07-24 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0002_paymentclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=10, unique=True)),
                ('mobile_money_network', models.CharField(blank=True, max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('mobile_money_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('payment_instructions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
